/**
* Submit form generated by bluesky_form shortcode
* added on 24-06-2021
*/

// function doSubmit(elem) {
// 	if(typeof elem == 'undefined' || elem == '' || elem === null){
// 		return;
// 	}
// 	elem.submit();
// }